-- Ventas / Punto de venta — ejecutar si erp.ventas aún no existe en la BD.
-- Si la tabla ya existe con esquema antiguo, ejecutar migration_fix_esquema_ventas.sql.
BEGIN;

CREATE TABLE IF NOT EXISTS erp.ventas (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  empresa_id BIGINT NOT NULL REFERENCES erp.empresas(id),
  cliente_id BIGINT NOT NULL,
  fecha_emision DATE NOT NULL,
  tipo_comprobante_codigo VARCHAR(20) NOT NULL,
  serie VARCHAR(10) NOT NULL,
  numero_comprobante VARCHAR(50) NOT NULL,
  moneda_codigo VARCHAR(6) NOT NULL DEFAULT 'PEN',
  total_gravado NUMERIC(18,2) NOT NULL CHECK (total_gravado >= 0),
  total_igv NUMERIC(18,2) NOT NULL CHECK (total_igv >= 0),
  total_venta NUMERIC(18,2) NOT NULL CHECK (total_venta >= 0),
  fecha_creacion TIMESTAMPTZ NOT NULL DEFAULT now(),
  usuario_creacion VARCHAR(64),
  fecha_modificacion TIMESTAMPTZ NOT NULL DEFAULT now(),
  usuario_modificacion VARCHAR(64),
  CONSTRAINT uq_ventas_empresa_id UNIQUE (empresa_id, id)
);

CREATE UNIQUE INDEX IF NOT EXISTS ux_ventas_empresa_id ON erp.ventas(empresa_id, id);

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'fk_ventas_cliente_multiempresa'
  ) THEN
    ALTER TABLE erp.ventas
      ADD CONSTRAINT fk_ventas_cliente_multiempresa
      FOREIGN KEY (empresa_id, cliente_id)
      REFERENCES erp.clientes(empresa_id, id);
  END IF;
END $$;

CREATE TABLE IF NOT EXISTS erp.ventas_detalle (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  empresa_id BIGINT NOT NULL REFERENCES erp.empresas(id),
  venta_id BIGINT NOT NULL,
  producto_id BIGINT NOT NULL,
  cantidad NUMERIC(18,4) NOT NULL CHECK (cantidad > 0),
  precio_unitario NUMERIC(18,6) NOT NULL CHECK (precio_unitario >= 0),
  lote_codigo VARCHAR(60) NOT NULL,
  subtotal NUMERIC(18,2) NOT NULL CHECK (subtotal >= 0),
  fecha_creacion TIMESTAMPTZ NOT NULL DEFAULT now(),
  usuario_creacion VARCHAR(64),
  fecha_modificacion TIMESTAMPTZ NOT NULL DEFAULT now(),
  usuario_modificacion VARCHAR(64),
  CONSTRAINT uq_ventas_detalle_empresa_id UNIQUE (empresa_id, id)
);

CREATE UNIQUE INDEX IF NOT EXISTS ux_ventas_detalle_empresa_id ON erp.ventas_detalle(empresa_id, id);

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'fk_ventas_detalle_venta_multiempresa'
  ) THEN
    ALTER TABLE erp.ventas_detalle
      ADD CONSTRAINT fk_ventas_detalle_venta_multiempresa
      FOREIGN KEY (empresa_id, venta_id)
      REFERENCES erp.ventas(empresa_id, id)
      ON DELETE CASCADE;
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'fk_ventas_detalle_producto_multiempresa'
  ) THEN
    ALTER TABLE erp.ventas_detalle
      ADD CONSTRAINT fk_ventas_detalle_producto_multiempresa
      FOREIGN KEY (empresa_id, producto_id)
      REFERENCES erp.productos(empresa_id, id);
  END IF;
END $$;

COMMIT;
