-- Ejecutar en bases donde ya existe erp sin las tablas de compras o sin stock en lotes.
-- PostgreSQL ≥ 12 recomendado (IF NOT EXISTS en ADD COLUMN desde PG 9.1 para column).

BEGIN;

ALTER TABLE erp.lotes ADD COLUMN IF NOT EXISTS stock_actual NUMERIC(18,4) NOT NULL DEFAULT 0;
ALTER TABLE erp.lotes DROP CONSTRAINT IF EXISTS chk_lotes_stock_actual_nonneg;
ALTER TABLE erp.lotes ADD CONSTRAINT chk_lotes_stock_actual_nonneg CHECK (stock_actual >= 0);

CREATE TABLE IF NOT EXISTS erp.compras (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  empresa_id BIGINT NOT NULL REFERENCES erp.empresas(id),
  proveedor_id BIGINT NOT NULL,
  fecha_ingreso DATE NOT NULL,
  almacen VARCHAR(150),
  tipo_comprobante_codigo VARCHAR(20) NOT NULL,
  numero_comprobante VARCHAR(80) NOT NULL,
  moneda_codigo VARCHAR(6) NOT NULL,
  fecha_creacion TIMESTAMPTZ NOT NULL DEFAULT now(),
  usuario_creacion VARCHAR(64),
  fecha_modificacion TIMESTAMPTZ NOT NULL DEFAULT now(),
  usuario_modificacion VARCHAR(64),
  CONSTRAINT uq_compras_empresa_id UNIQUE (empresa_id, id)
);

CREATE UNIQUE INDEX IF NOT EXISTS ux_compras_empresa_id ON erp.compras(empresa_id, id);

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'fk_compras_proveedor_multiempresa'
  ) THEN
    ALTER TABLE erp.compras
      ADD CONSTRAINT fk_compras_proveedor_multiempresa
      FOREIGN KEY (empresa_id, proveedor_id)
      REFERENCES erp.proveedores(empresa_id, id);
  END IF;
END $$;

CREATE TABLE IF NOT EXISTS erp.compras_detalle (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  empresa_id BIGINT NOT NULL REFERENCES erp.empresas(id),
  compra_id BIGINT NOT NULL,
  producto_id BIGINT NOT NULL,
  cantidad NUMERIC(18,4) NOT NULL CHECK (cantidad > 0),
  precio_unitario NUMERIC(18,6) NOT NULL CHECK (precio_unitario >= 0),
  lote_codigo VARCHAR(60) NOT NULL,
  fecha_produccion DATE,
  fecha_vencimiento DATE,
  fecha_creacion TIMESTAMPTZ NOT NULL DEFAULT now(),
  usuario_creacion VARCHAR(64),
  fecha_modificacion TIMESTAMPTZ NOT NULL DEFAULT now(),
  usuario_modificacion VARCHAR(64),
  CONSTRAINT uq_compras_detalle_empresa_id UNIQUE (empresa_id, id)
);

CREATE UNIQUE INDEX IF NOT EXISTS ux_compras_detalle_empresa_id ON erp.compras_detalle(empresa_id, id);

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'fk_compras_detalle_compra_multiempresa'
  ) THEN
    ALTER TABLE erp.compras_detalle
      ADD CONSTRAINT fk_compras_detalle_compra_multiempresa
      FOREIGN KEY (empresa_id, compra_id)
      REFERENCES erp.compras(empresa_id, id)
      ON DELETE CASCADE;
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'fk_compras_detalle_producto_multiempresa'
  ) THEN
    ALTER TABLE erp.compras_detalle
      ADD CONSTRAINT fk_compras_detalle_producto_multiempresa
      FOREIGN KEY (empresa_id, producto_id)
      REFERENCES erp.productos(empresa_id, id);
  END IF;
END $$;

COMMIT;
