-- ERP Distribuidora (PostgreSQL) - Modelo Core/Configuración/Maestros (multiempresa)
-- Nota:
-- 1) Este script está pensado para una primera versión del módulo.
-- 2) Incluye catálogos SUNAT mínimos (tipo de persona, tipo de documento, IGV, moneda, tipo comprobante).
-- 3) Para tablas multiempresa, se incluye `empresa_id` y se usan FKs compuestas cuando aplica.

BEGIN;

CREATE SCHEMA IF NOT EXISTS erp;

-- =========================
-- Catálogos (globales)
-- =========================

CREATE TABLE IF NOT EXISTS erp.catalogo_tipo_persona (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  codigo VARCHAR(10) NOT NULL UNIQUE, -- e.g., 'N' (Natural), 'J' (Jurídica) - ajustable según tu catálogo SUNAT
  nombre VARCHAR(100) NOT NULL,
  activo BOOLEAN NOT NULL DEFAULT TRUE,
  fecha_creacion TIMESTAMPTZ NOT NULL DEFAULT now(),
  usuario_creacion VARCHAR(64),
  fecha_modificacion TIMESTAMPTZ NOT NULL DEFAULT now(),
  usuario_modificacion VARCHAR(64)
);

CREATE TABLE IF NOT EXISTS erp.catalogo_tipo_documento (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  codigo_sunat VARCHAR(10) NOT NULL UNIQUE, -- e.g., '1' DNI, '6' RUC, etc. (según tu parametrización)
  nombre VARCHAR(120) NOT NULL,
  longitud INTEGER NOT NULL CHECK (longitud > 0),
  tipo_persona_id BIGINT NOT NULL REFERENCES erp.catalogo_tipo_persona(id),
  activo BOOLEAN NOT NULL DEFAULT TRUE,
  fecha_creacion TIMESTAMPTZ NOT NULL DEFAULT now(),
  usuario_creacion VARCHAR(64),
  fecha_modificacion TIMESTAMPTZ NOT NULL DEFAULT now(),
  usuario_modificacion VARCHAR(64)
);

CREATE TABLE IF NOT EXISTS erp.catalogo_tipo_igv (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  codigo VARCHAR(20) NOT NULL UNIQUE, -- e.g., 'IGV18'
  nombre VARCHAR(120) NOT NULL,
  porcentaje NUMERIC(6,3) NOT NULL CHECK (porcentaje >= 0),
  activo BOOLEAN NOT NULL DEFAULT TRUE,
  fecha_creacion TIMESTAMPTZ NOT NULL DEFAULT now(),
  usuario_creacion VARCHAR(64),
  fecha_modificacion TIMESTAMPTZ NOT NULL DEFAULT now(),
  usuario_modificacion VARCHAR(64)
);

CREATE TABLE IF NOT EXISTS erp.catalogo_moneda (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  codigo_iso CHAR(3) NOT NULL UNIQUE, -- e.g., 'PEN', 'USD'
  nombre VARCHAR(80) NOT NULL,
  simbolo VARCHAR(10),
  activo BOOLEAN NOT NULL DEFAULT TRUE,
  fecha_creacion TIMESTAMPTZ NOT NULL DEFAULT now(),
  usuario_creacion VARCHAR(64),
  fecha_modificacion TIMESTAMPTZ NOT NULL DEFAULT now(),
  usuario_modificacion VARCHAR(64)
);

CREATE TABLE IF NOT EXISTS erp.catalogo_tipo_zona (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  codigo VARCHAR(20) NOT NULL UNIQUE,
  nombre VARCHAR(120) NOT NULL,
  activo BOOLEAN NOT NULL DEFAULT TRUE,
  fecha_creacion TIMESTAMPTZ NOT NULL DEFAULT now(),
  usuario_creacion VARCHAR(64),
  fecha_modificacion TIMESTAMPTZ NOT NULL DEFAULT now(),
  usuario_modificacion VARCHAR(64)
);

CREATE TABLE IF NOT EXISTS erp.catalogo_tipo_vehiculo (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  codigo VARCHAR(20) NOT NULL UNIQUE,
  nombre VARCHAR(120) NOT NULL,
  activo BOOLEAN NOT NULL DEFAULT TRUE,
  fecha_creacion TIMESTAMPTZ NOT NULL DEFAULT now(),
  usuario_creacion VARCHAR(64),
  fecha_modificacion TIMESTAMPTZ NOT NULL DEFAULT now(),
  usuario_modificacion VARCHAR(64)
);

CREATE TABLE IF NOT EXISTS erp.catalogo_tipo_comprobante (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  codigo_sunat VARCHAR(10) NOT NULL UNIQUE, -- e.g., '01' Factura, etc. (según parametrización)
  nombre VARCHAR(150) NOT NULL,             -- e.g., 'FACTURA'
  requiere_serie BOOLEAN NOT NULL DEFAULT TRUE,
  activo BOOLEAN NOT NULL DEFAULT TRUE,
  fecha_creacion TIMESTAMPTZ NOT NULL DEFAULT now(),
  usuario_creacion VARCHAR(64),
  fecha_modificacion TIMESTAMPTZ NOT NULL DEFAULT now(),
  usuario_modificacion VARCHAR(64)
);

-- UBIGEO mínimo (SUNAT). Población masiva se hará fuera de este script.
CREATE TABLE IF NOT EXISTS erp.catalogo_ubigeo (
  codigo_ubigeo CHAR(6) PRIMARY KEY,
  distrito VARCHAR(120) NOT NULL,
  provincia VARCHAR(120) NOT NULL,
  departamento VARCHAR(120) NOT NULL
);

-- =========================
-- Core multiempresa
-- =========================

CREATE TABLE IF NOT EXISTS erp.empresas (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ruc VARCHAR(15) NOT NULL UNIQUE,
  razon_social VARCHAR(200) NOT NULL,
  email VARCHAR(150),
  telefono VARCHAR(30),
  direccion VARCHAR(250),
  ubigeo_codigo CHAR(6) REFERENCES erp.catalogo_ubigeo(codigo_ubigeo),
  activo BOOLEAN NOT NULL DEFAULT TRUE,
  fecha_creacion TIMESTAMPTZ NOT NULL DEFAULT now(),
  usuario_creacion VARCHAR(64),
  fecha_modificacion TIMESTAMPTZ NOT NULL DEFAULT now(),
  usuario_modificacion VARCHAR(64)
);

CREATE TABLE IF NOT EXISTS erp.configuracion_empresa (
  empresa_id BIGINT PRIMARY KEY REFERENCES erp.empresas(id),
  moneda_default_id BIGINT NOT NULL REFERENCES erp.catalogo_moneda(id),
  tipo_igv_default_id BIGINT NOT NULL REFERENCES erp.catalogo_tipo_igv(id),
  timezone VARCHAR(50) NOT NULL DEFAULT 'America/Lima',
  ambiente_sunat VARCHAR(20) NOT NULL DEFAULT 'PRODUCCION', -- ajuste según tu parametrización
  activo BOOLEAN NOT NULL DEFAULT TRUE,
  fecha_creacion TIMESTAMPTZ NOT NULL DEFAULT now(),
  usuario_creacion VARCHAR(64),
  fecha_modificacion TIMESTAMPTZ NOT NULL DEFAULT now(),
  usuario_modificacion VARCHAR(64)
);

-- =========================
-- Catálogos operativos
-- =========================

CREATE TABLE IF NOT EXISTS erp.unidades_medida (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  codigo VARCHAR(20) NOT NULL UNIQUE, -- e.g., 'UND', 'KG'
  nombre VARCHAR(120) NOT NULL,
  abreviatura VARCHAR(30),
  activo BOOLEAN NOT NULL DEFAULT TRUE,
  fecha_creacion TIMESTAMPTZ NOT NULL DEFAULT now(),
  usuario_creacion VARCHAR(64),
  fecha_modificacion TIMESTAMPTZ NOT NULL DEFAULT now(),
  usuario_modificacion VARCHAR(64)
);

-- =========================
-- Maestros - Productos
-- =========================

CREATE TABLE IF NOT EXISTS erp.clases_productos (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  empresa_id BIGINT NOT NULL REFERENCES erp.empresas(id),
  codigo VARCHAR(30) NOT NULL,
  nombre VARCHAR(150) NOT NULL,
  descripcion TEXT,
  activo BOOLEAN NOT NULL DEFAULT TRUE,
  fecha_creacion TIMESTAMPTZ NOT NULL DEFAULT now(),
  usuario_creacion VARCHAR(64),
  fecha_modificacion TIMESTAMPTZ NOT NULL DEFAULT now(),
  usuario_modificacion VARCHAR(64),
  CONSTRAINT uq_clases_productos_empresa_codigo UNIQUE (empresa_id, codigo),
  CONSTRAINT uq_clases_productos_empresa_id UNIQUE (empresa_id, id)
);

-- Garantiza unicidad compuesta para FKs multiempresa
CREATE UNIQUE INDEX IF NOT EXISTS ux_clases_productos_empresa_id ON erp.clases_productos(empresa_id, id);

CREATE TABLE IF NOT EXISTS erp.productos (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  empresa_id BIGINT NOT NULL REFERENCES erp.empresas(id),
  clase_producto_id BIGINT NOT NULL,
  codigo VARCHAR(60) NOT NULL,
  nombre VARCHAR(200) NOT NULL,
  descripcion TEXT,
  unidad_medida_base_id BIGINT NOT NULL REFERENCES erp.unidades_medida(id),
  tipo_igv_id BIGINT NOT NULL REFERENCES erp.catalogo_tipo_igv(id),
  activo BOOLEAN NOT NULL DEFAULT TRUE,
  fecha_creacion TIMESTAMPTZ NOT NULL DEFAULT now(),
  usuario_creacion VARCHAR(64),
  fecha_modificacion TIMESTAMPTZ NOT NULL DEFAULT now(),
  usuario_modificacion VARCHAR(64),
  CONSTRAINT uq_productos_empresa_codigo UNIQUE (empresa_id, codigo),
  CONSTRAINT uq_productos_empresa_id UNIQUE (empresa_id, id)
);

ALTER TABLE erp.productos
  ADD CONSTRAINT fk_productos_clase_producto_multiempresa
  FOREIGN KEY (empresa_id, clase_producto_id)
  REFERENCES erp.clases_productos(empresa_id, id);

-- Presentaciones: catálogo por empresa (definición “cómo se expresa” la unidad)
CREATE TABLE IF NOT EXISTS erp.presentaciones (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  empresa_id BIGINT NOT NULL REFERENCES erp.empresas(id),
  codigo VARCHAR(30) NOT NULL,
  nombre VARCHAR(150) NOT NULL,
  unidad_medida_id BIGINT NOT NULL REFERENCES erp.unidades_medida(id),
  activo BOOLEAN NOT NULL DEFAULT TRUE,
  fecha_creacion TIMESTAMPTZ NOT NULL DEFAULT now(),
  usuario_creacion VARCHAR(64),
  fecha_modificacion TIMESTAMPTZ NOT NULL DEFAULT now(),
  usuario_modificacion VARCHAR(64),
  CONSTRAINT uq_presentaciones_empresa_codigo UNIQUE (empresa_id, codigo),
  CONSTRAINT uq_presentaciones_empresa_id UNIQUE (empresa_id, id)
);

CREATE UNIQUE INDEX IF NOT EXISTS ux_presentaciones_empresa_id ON erp.presentaciones(empresa_id, id);

-- Producto-Presentación: relación con factor (cantidad de unidad base por 1 presentación)
CREATE TABLE IF NOT EXISTS erp.productos_presentaciones (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  empresa_id BIGINT NOT NULL REFERENCES erp.empresas(id),
  producto_id BIGINT NOT NULL,
  presentacion_id BIGINT NOT NULL,
  factor NUMERIC(18,6) NOT NULL CHECK (factor > 0), -- 1 presentacion = factor * unidad_medida_base
  activo BOOLEAN NOT NULL DEFAULT TRUE,
  fecha_creacion TIMESTAMPTZ NOT NULL DEFAULT now(),
  usuario_creacion VARCHAR(64),
  fecha_modificacion TIMESTAMPTZ NOT NULL DEFAULT now(),
  usuario_modificacion VARCHAR(64),
  CONSTRAINT uq_productos_presentaciones_rel UNIQUE (empresa_id, producto_id, presentacion_id),
  CONSTRAINT uq_productos_presentaciones_empresa_id UNIQUE (empresa_id, id)
);

CREATE UNIQUE INDEX IF NOT EXISTS ux_productos_presentaciones_empresa_id ON erp.productos_presentaciones(empresa_id, id);

ALTER TABLE erp.productos_presentaciones
  ADD CONSTRAINT fk_pp_producto_multiempresa
  FOREIGN KEY (empresa_id, producto_id)
  REFERENCES erp.productos(empresa_id, id);

ALTER TABLE erp.productos_presentaciones
  ADD CONSTRAINT fk_pp_presentacion_multiempresa
  FOREIGN KEY (empresa_id, presentacion_id)
  REFERENCES erp.presentaciones(empresa_id, id);

-- =========================
-- Maestros - Precios (lista + vigencia)
-- =========================

CREATE TABLE IF NOT EXISTS erp.listas_precios (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  empresa_id BIGINT NOT NULL REFERENCES erp.empresas(id),
  codigo VARCHAR(30) NOT NULL,
  nombre VARCHAR(150) NOT NULL,
  moneda_id BIGINT NOT NULL REFERENCES erp.catalogo_moneda(id),
  fecha_inicio DATE NOT NULL DEFAULT CURRENT_DATE,
  fecha_fin DATE,
  activo BOOLEAN NOT NULL DEFAULT TRUE,
  fecha_creacion TIMESTAMPTZ NOT NULL DEFAULT now(),
  usuario_creacion VARCHAR(64),
  fecha_modificacion TIMESTAMPTZ NOT NULL DEFAULT now(),
  usuario_modificacion VARCHAR(64),
  CONSTRAINT uq_listas_precios_empresa_codigo UNIQUE (empresa_id, codigo),
  CONSTRAINT uq_listas_precios_empresa_id UNIQUE (empresa_id, id)
);

CREATE UNIQUE INDEX IF NOT EXISTS ux_listas_precios_empresa_id ON erp.listas_precios(empresa_id, id);

CREATE TABLE IF NOT EXISTS erp.precios (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  empresa_id BIGINT NOT NULL REFERENCES erp.empresas(id),
  lista_precio_id BIGINT NOT NULL,
  producto_presentacion_id BIGINT NOT NULL,
  precio_unitario NUMERIC(18,4) NOT NULL CHECK (precio_unitario >= 0),
  impuesto_incluido BOOLEAN NOT NULL DEFAULT FALSE,
  fecha_inicio DATE NOT NULL DEFAULT CURRENT_DATE,
  fecha_fin DATE,
  activo BOOLEAN NOT NULL DEFAULT TRUE,
  fecha_creacion TIMESTAMPTZ NOT NULL DEFAULT now(),
  usuario_creacion VARCHAR(64),
  fecha_modificacion TIMESTAMPTZ NOT NULL DEFAULT now(),
  usuario_modificacion VARCHAR(64),
  CONSTRAINT uq_precios UNIQUE (empresa_id, lista_precio_id, producto_presentacion_id, fecha_inicio)
);

CREATE UNIQUE INDEX IF NOT EXISTS ux_precios_empresa_id ON erp.precios(empresa_id, id);

ALTER TABLE erp.precios
  ADD CONSTRAINT fk_precios_lista_multiempresa
  FOREIGN KEY (empresa_id, lista_precio_id)
  REFERENCES erp.listas_precios(empresa_id, id);

ALTER TABLE erp.precios
  ADD CONSTRAINT fk_precios_producto_presentacion_multiempresa
  FOREIGN KEY (empresa_id, producto_presentacion_id)
  REFERENCES erp.productos_presentaciones(empresa_id, id);

-- =========================
-- Maestros - Personas (clientes/proveedores/conductores)
-- =========================

CREATE TABLE IF NOT EXISTS erp.personas (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  empresa_id BIGINT NOT NULL REFERENCES erp.empresas(id),
  tipo_persona_id BIGINT NOT NULL REFERENCES erp.catalogo_tipo_persona(id),
  tipo_documento_id BIGINT NOT NULL REFERENCES erp.catalogo_tipo_documento(id),
  numero_documento VARCHAR(25) NOT NULL,
  razon_social_nombre VARCHAR(200) NOT NULL, -- para natural y jurídica (normaliza la UI; en especializaciones puedes separar)
  apellido_paterno VARCHAR(100),
  apellido_materno VARCHAR(100),
  nombres VARCHAR(150),
  email VARCHAR(150),
  telefono VARCHAR(30),
  direccion VARCHAR(250),
  nombre_comercial VARCHAR(200),
  estado_sunat VARCHAR(40),
  condicion_sunat VARCHAR(40),
  genero CHAR(1),
  es_contribuyente BOOLEAN NOT NULL DEFAULT FALSE,
  ubigeo_codigo CHAR(6) REFERENCES erp.catalogo_ubigeo(codigo_ubigeo),
  activo BOOLEAN NOT NULL DEFAULT TRUE,
  fecha_creacion TIMESTAMPTZ NOT NULL DEFAULT now(),
  usuario_creacion VARCHAR(64),
  fecha_modificacion TIMESTAMPTZ NOT NULL DEFAULT now(),
  usuario_modificacion VARCHAR(64),
  CONSTRAINT uq_personas_empresa_doc UNIQUE (empresa_id, tipo_documento_id, numero_documento),
  CONSTRAINT uq_personas_empresa_id UNIQUE (empresa_id, id)
);

CREATE UNIQUE INDEX IF NOT EXISTS ux_personas_empresa_id ON erp.personas(empresa_id, id);

CREATE TABLE IF NOT EXISTS erp.clientes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  empresa_id BIGINT NOT NULL REFERENCES erp.empresas(id),
  persona_id BIGINT NOT NULL,
  codigo_cliente VARCHAR(30) NOT NULL,
  limite_credito NUMERIC(18,2) NOT NULL DEFAULT 0 CHECK (limite_credito >= 0),
  activo BOOLEAN NOT NULL DEFAULT TRUE,
  fecha_creacion TIMESTAMPTZ NOT NULL DEFAULT now(),
  usuario_creacion VARCHAR(64),
  fecha_modificacion TIMESTAMPTZ NOT NULL DEFAULT now(),
  usuario_modificacion VARCHAR(64),
  CONSTRAINT uq_clientes_empresa_codigo UNIQUE (empresa_id, codigo_cliente),
  CONSTRAINT uq_clientes_empresa_persona UNIQUE (empresa_id, persona_id)
);

CREATE UNIQUE INDEX IF NOT EXISTS ux_clientes_empresa_id ON erp.clientes(empresa_id, id);

ALTER TABLE erp.clientes
  ADD CONSTRAINT fk_clientes_persona_multiempresa
  FOREIGN KEY (empresa_id, persona_id)
  REFERENCES erp.personas(empresa_id, id);

CREATE TABLE IF NOT EXISTS erp.proveedores (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  empresa_id BIGINT NOT NULL REFERENCES erp.empresas(id),
  persona_id BIGINT NOT NULL,
  codigo_proveedor VARCHAR(30) NOT NULL,
  plazo_credito_dias INTEGER CHECK (plazo_credito_dias IS NULL OR plazo_credito_dias >= 0),
  cuenta_soles VARCHAR(40),
  activo BOOLEAN NOT NULL DEFAULT TRUE,
  fecha_creacion TIMESTAMPTZ NOT NULL DEFAULT now(),
  usuario_creacion VARCHAR(64),
  fecha_modificacion TIMESTAMPTZ NOT NULL DEFAULT now(),
  usuario_modificacion VARCHAR(64),
  CONSTRAINT uq_proveedores_empresa_codigo UNIQUE (empresa_id, codigo_proveedor),
  CONSTRAINT uq_proveedores_empresa_persona UNIQUE (empresa_id, persona_id)
);

CREATE UNIQUE INDEX IF NOT EXISTS ux_proveedores_empresa_id ON erp.proveedores(empresa_id, id);

ALTER TABLE erp.proveedores
  ADD CONSTRAINT fk_proveedores_persona_multiempresa
  FOREIGN KEY (empresa_id, persona_id)
  REFERENCES erp.personas(empresa_id, id);

-- Conductores: especialización con licencia y datos operativos
CREATE TABLE IF NOT EXISTS erp.conductores (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  empresa_id BIGINT NOT NULL REFERENCES erp.empresas(id),
  persona_id BIGINT NOT NULL,
  licencia_numero VARCHAR(30),
  categoria_licencia VARCHAR(20),
  fecha_vencimiento_licencia DATE,
  activo BOOLEAN NOT NULL DEFAULT TRUE,
  fecha_creacion TIMESTAMPTZ NOT NULL DEFAULT now(),
  usuario_creacion VARCHAR(64),
  fecha_modificacion TIMESTAMPTZ NOT NULL DEFAULT now(),
  usuario_modificacion VARCHAR(64),
  CONSTRAINT uq_conductores_empresa_persona UNIQUE (empresa_id, persona_id)
);

CREATE UNIQUE INDEX IF NOT EXISTS ux_conductores_empresa_id ON erp.conductores(empresa_id, id);

ALTER TABLE erp.conductores
  ADD CONSTRAINT fk_conductores_persona_multiempresa
  FOREIGN KEY (empresa_id, persona_id)
  REFERENCES erp.personas(empresa_id, id);

-- =========================
-- Maestros - Logística (zonas y lotes)
-- =========================

CREATE TABLE IF NOT EXISTS erp.zonas (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  empresa_id BIGINT NOT NULL REFERENCES erp.empresas(id),
  tipo_zona_id BIGINT NOT NULL REFERENCES erp.catalogo_tipo_zona(id),
  codigo VARCHAR(30) NOT NULL,
  nombre VARCHAR(150) NOT NULL,
  descripcion TEXT,
  activo BOOLEAN NOT NULL DEFAULT TRUE,
  fecha_creacion TIMESTAMPTZ NOT NULL DEFAULT now(),
  usuario_creacion VARCHAR(64),
  fecha_modificacion TIMESTAMPTZ NOT NULL DEFAULT now(),
  usuario_modificacion VARCHAR(64),
  CONSTRAINT uq_zonas_empresa_codigo UNIQUE (empresa_id, codigo),
  CONSTRAINT uq_zonas_empresa_id UNIQUE (empresa_id, id)
);

CREATE UNIQUE INDEX IF NOT EXISTS ux_zonas_empresa_id ON erp.zonas(empresa_id, id);

CREATE TABLE IF NOT EXISTS erp.lotes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  empresa_id BIGINT NOT NULL REFERENCES erp.empresas(id),
  producto_id BIGINT NOT NULL,
  codigo_lote VARCHAR(60) NOT NULL,
  fecha_fabricacion DATE,
  fecha_vencimiento DATE,
  stock_actual NUMERIC(18,4) NOT NULL DEFAULT 0 CHECK (stock_actual >= 0),
  referencia_documento VARCHAR(80),
  activo BOOLEAN NOT NULL DEFAULT TRUE,
  fecha_creacion TIMESTAMPTZ NOT NULL DEFAULT now(),
  usuario_creacion VARCHAR(64),
  fecha_modificacion TIMESTAMPTZ NOT NULL DEFAULT now(),
  usuario_modificacion VARCHAR(64),
  CONSTRAINT uq_lotes_empresa_producto_codigo UNIQUE (empresa_id, producto_id, codigo_lote),
  CONSTRAINT uq_lotes_empresa_id UNIQUE (empresa_id, id)
);

CREATE UNIQUE INDEX IF NOT EXISTS ux_lotes_empresa_id ON erp.lotes(empresa_id, id);

ALTER TABLE erp.lotes
  ADD CONSTRAINT fk_lotes_producto_multiempresa
  FOREIGN KEY (empresa_id, producto_id)
  REFERENCES erp.productos(empresa_id, id);

-- Historial de ubicación “actual” usando rango de fechas
CREATE TABLE IF NOT EXISTS erp.lotes_ubicaciones (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  empresa_id BIGINT NOT NULL REFERENCES erp.empresas(id),
  lote_id BIGINT NOT NULL,
  zona_id BIGINT NOT NULL,
  fecha_desde TIMESTAMPTZ NOT NULL DEFAULT now(),
  fecha_hasta TIMESTAMPTZ,
  activo BOOLEAN NOT NULL DEFAULT TRUE,
  fecha_creacion TIMESTAMPTZ NOT NULL DEFAULT now(),
  usuario_creacion VARCHAR(64),
  fecha_modificacion TIMESTAMPTZ NOT NULL DEFAULT now(),
  usuario_modificacion VARCHAR(64)
);

CREATE UNIQUE INDEX IF NOT EXISTS ux_lotes_ubicaciones_empresa_id ON erp.lotes_ubicaciones(empresa_id, id);

ALTER TABLE erp.lotes_ubicaciones
  ADD CONSTRAINT fk_lotes_ubicaciones_lote_multiempresa
  FOREIGN KEY (empresa_id, lote_id)
  REFERENCES erp.lotes(empresa_id, id);

ALTER TABLE erp.lotes_ubicaciones
  ADD CONSTRAINT fk_lotes_ubicaciones_zona_multiempresa
  FOREIGN KEY (empresa_id, zona_id)
  REFERENCES erp.zonas(empresa_id, id);

-- Garantiza 1 ubicación “actual” por lote (fecha_hasta IS NULL)
CREATE UNIQUE INDEX IF NOT EXISTS ux_lotes_ubicaciones_lote_actual
  ON erp.lotes_ubicaciones(lote_id)
  WHERE fecha_hasta IS NULL;

-- =========================
-- Maestros - Transporte (vehículos)
-- =========================

CREATE TABLE IF NOT EXISTS erp.vehiculos (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  empresa_id BIGINT NOT NULL REFERENCES erp.empresas(id),
  tipo_vehiculo_id BIGINT NOT NULL REFERENCES erp.catalogo_tipo_vehiculo(id),
  placa VARCHAR(15) NOT NULL,
  marca VARCHAR(60),
  modelo VARCHAR(60),
  capacidad VARCHAR(60), -- ajustable a modelo futuro (kg, ton, etc.)
  activo BOOLEAN NOT NULL DEFAULT TRUE,
  fecha_creacion TIMESTAMPTZ NOT NULL DEFAULT now(),
  usuario_creacion VARCHAR(64),
  fecha_modificacion TIMESTAMPTZ NOT NULL DEFAULT now(),
  usuario_modificacion VARCHAR(64),
  CONSTRAINT uq_vehiculos_empresa_placa UNIQUE (empresa_id, placa)
);

CREATE UNIQUE INDEX IF NOT EXISTS ux_vehiculos_empresa_id ON erp.vehiculos(empresa_id, id);

-- =========================
-- Configuración - Punto de venta y series SUNAT
-- =========================

CREATE TABLE IF NOT EXISTS erp.puntos_venta (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  empresa_id BIGINT NOT NULL REFERENCES erp.empresas(id),
  codigo VARCHAR(30) NOT NULL,
  nombre VARCHAR(150) NOT NULL,
  direccion VARCHAR(250),
  ubigeo_codigo CHAR(6) REFERENCES erp.catalogo_ubigeo(codigo_ubigeo),
  zona_almacen_defecto_id BIGINT,
  activo BOOLEAN NOT NULL DEFAULT TRUE,
  fecha_creacion TIMESTAMPTZ NOT NULL DEFAULT now(),
  usuario_creacion VARCHAR(64),
  fecha_modificacion TIMESTAMPTZ NOT NULL DEFAULT now(),
  usuario_modificacion VARCHAR(64),
  CONSTRAINT uq_puntos_venta_empresa_codigo UNIQUE (empresa_id, codigo),
  CONSTRAINT uq_puntos_venta_empresa_id UNIQUE (empresa_id, id),
  CONSTRAINT chk_puntos_venta_zona_almacen_defecto_null_or_empresa
    CHECK (zona_almacen_defecto_id IS NULL OR zona_almacen_defecto_id > 0)
);

CREATE UNIQUE INDEX IF NOT EXISTS ux_puntos_venta_empresa_id ON erp.puntos_venta(empresa_id, id);

-- FK opcional por zona (multiempresa)
ALTER TABLE erp.puntos_venta
  ADD CONSTRAINT fk_puntos_venta_zona_multiempresa
  FOREIGN KEY (empresa_id, zona_almacen_defecto_id)
  REFERENCES erp.zonas(empresa_id, id);

CREATE TABLE IF NOT EXISTS erp.series_comprobantes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  empresa_id BIGINT NOT NULL REFERENCES erp.empresas(id),
  punto_venta_id BIGINT NOT NULL,
  tipo_comprobante_id BIGINT NOT NULL REFERENCES erp.catalogo_tipo_comprobante(id),
  serie VARCHAR(10) NOT NULL,
  correlativo_actual BIGINT NOT NULL DEFAULT 1 CHECK (correlativo_actual >= 1),
  fecha_inicio DATE NOT NULL DEFAULT CURRENT_DATE,
  fecha_fin DATE,
  activo BOOLEAN NOT NULL DEFAULT TRUE,
  fecha_creacion TIMESTAMPTZ NOT NULL DEFAULT now(),
  usuario_creacion VARCHAR(64),
  fecha_modificacion TIMESTAMPTZ NOT NULL DEFAULT now(),
  usuario_modificacion VARCHAR(64),
  CONSTRAINT uq_series_comprobantes UNIQUE (empresa_id, punto_venta_id, tipo_comprobante_id, serie)
);

CREATE UNIQUE INDEX IF NOT EXISTS ux_series_comprobantes_empresa_id ON erp.series_comprobantes(empresa_id, id);

ALTER TABLE erp.series_comprobantes
  ADD CONSTRAINT fk_series_comprobantes_punto_venta_multiempresa
  FOREIGN KEY (empresa_id, punto_venta_id)
  REFERENCES erp.puntos_venta(empresa_id, id);

-- =========================
-- Compras — ingreso de mercadería / facturas de proveedor
-- =========================

CREATE TABLE IF NOT EXISTS erp.compras (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  empresa_id BIGINT NOT NULL REFERENCES erp.empresas(id),
  proveedor_id BIGINT NOT NULL,
  fecha_ingreso DATE NOT NULL,
  almacen VARCHAR(150),
  tipo_comprobante_codigo VARCHAR(20) NOT NULL,
  numero_comprobante VARCHAR(80) NOT NULL,
  moneda_codigo VARCHAR(6) NOT NULL,
  fecha_creacion TIMESTAMPTZ NOT NULL DEFAULT now(),
  usuario_creacion VARCHAR(64),
  fecha_modificacion TIMESTAMPTZ NOT NULL DEFAULT now(),
  usuario_modificacion VARCHAR(64),
  CONSTRAINT uq_compras_empresa_id UNIQUE (empresa_id, id)
);

CREATE UNIQUE INDEX IF NOT EXISTS ux_compras_empresa_id ON erp.compras(empresa_id, id);

ALTER TABLE erp.compras
  ADD CONSTRAINT fk_compras_proveedor_multiempresa
  FOREIGN KEY (empresa_id, proveedor_id)
  REFERENCES erp.proveedores(empresa_id, id);

CREATE TABLE IF NOT EXISTS erp.compras_detalle (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  empresa_id BIGINT NOT NULL REFERENCES erp.empresas(id),
  compra_id BIGINT NOT NULL,
  producto_id BIGINT NOT NULL,
  cantidad NUMERIC(18,4) NOT NULL CHECK (cantidad > 0),
  precio_unitario NUMERIC(18,6) NOT NULL CHECK (precio_unitario >= 0),
  lote_codigo VARCHAR(60) NOT NULL,
  fecha_produccion DATE,
  fecha_vencimiento DATE,
  fecha_creacion TIMESTAMPTZ NOT NULL DEFAULT now(),
  usuario_creacion VARCHAR(64),
  fecha_modificacion TIMESTAMPTZ NOT NULL DEFAULT now(),
  usuario_modificacion VARCHAR(64),
  CONSTRAINT uq_compras_detalle_empresa_id UNIQUE (empresa_id, id)
);

CREATE UNIQUE INDEX IF NOT EXISTS ux_compras_detalle_empresa_id ON erp.compras_detalle(empresa_id, id);

ALTER TABLE erp.compras_detalle
  ADD CONSTRAINT fk_compras_detalle_compra_multiempresa
  FOREIGN KEY (empresa_id, compra_id)
  REFERENCES erp.compras(empresa_id, id)
  ON DELETE CASCADE;

ALTER TABLE erp.compras_detalle
  ADD CONSTRAINT fk_compras_detalle_producto_multiempresa
  FOREIGN KEY (empresa_id, producto_id)
  REFERENCES erp.productos(empresa_id, id);

-- =========================
-- Ventas — punto de venta / facturación directa
-- =========================

CREATE TABLE IF NOT EXISTS erp.ventas (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  empresa_id BIGINT NOT NULL REFERENCES erp.empresas(id),
  cliente_id BIGINT NOT NULL,
  fecha_emision DATE NOT NULL,
  tipo_comprobante_codigo VARCHAR(20) NOT NULL,
  serie VARCHAR(10) NOT NULL,
  numero_comprobante VARCHAR(20) NOT NULL,
  moneda_codigo VARCHAR(6) NOT NULL,
  total_gravado NUMERIC(18,2) NOT NULL CHECK (total_gravado >= 0),
  total_igv NUMERIC(18,2) NOT NULL CHECK (total_igv >= 0),
  total_venta NUMERIC(18,2) NOT NULL CHECK (total_venta >= 0),
  fecha_creacion TIMESTAMPTZ NOT NULL DEFAULT now(),
  usuario_creacion VARCHAR(64),
  fecha_modificacion TIMESTAMPTZ NOT NULL DEFAULT now(),
  usuario_modificacion VARCHAR(64),
  CONSTRAINT uq_ventas_empresa_id UNIQUE (empresa_id, id)
);

CREATE UNIQUE INDEX IF NOT EXISTS ux_ventas_empresa_id ON erp.ventas(empresa_id, id);

ALTER TABLE erp.ventas
  ADD CONSTRAINT fk_ventas_cliente_multiempresa
  FOREIGN KEY (empresa_id, cliente_id)
  REFERENCES erp.clientes(empresa_id, id);

CREATE TABLE IF NOT EXISTS erp.ventas_detalle (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  empresa_id BIGINT NOT NULL REFERENCES erp.empresas(id),
  venta_id BIGINT NOT NULL,
  producto_id BIGINT NOT NULL,
  cantidad NUMERIC(18,4) NOT NULL CHECK (cantidad > 0),
  precio_unitario NUMERIC(18,6) NOT NULL CHECK (precio_unitario >= 0),
  lote_codigo VARCHAR(60) NOT NULL,
  subtotal NUMERIC(18,2) NOT NULL CHECK (subtotal >= 0),
  fecha_creacion TIMESTAMPTZ NOT NULL DEFAULT now(),
  usuario_creacion VARCHAR(64),
  fecha_modificacion TIMESTAMPTZ NOT NULL DEFAULT now(),
  usuario_modificacion VARCHAR(64),
  CONSTRAINT uq_ventas_detalle_empresa_id UNIQUE (empresa_id, id)
);

CREATE UNIQUE INDEX IF NOT EXISTS ux_ventas_detalle_empresa_id ON erp.ventas_detalle(empresa_id, id);

ALTER TABLE erp.ventas_detalle
  ADD CONSTRAINT fk_ventas_detalle_venta_multiempresa
  FOREIGN KEY (empresa_id, venta_id)
  REFERENCES erp.ventas(empresa_id, id)
  ON DELETE CASCADE;

ALTER TABLE erp.ventas_detalle
  ADD CONSTRAINT fk_ventas_detalle_producto_multiempresa
  FOREIGN KEY (empresa_id, producto_id)
  REFERENCES erp.productos(empresa_id, id);

-- =========================
-- Seguridad - Usuarios / Login (multiempresa)
-- =========================

CREATE TABLE IF NOT EXISTS erp.usuarios (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  empresa_id BIGINT NOT NULL REFERENCES erp.empresas(id),
  persona_id BIGINT NOT NULL,
  nombre_usuario VARCHAR(50) NOT NULL,
  password_hash VARCHAR(255) NOT NULL,
  activo BOOLEAN NOT NULL DEFAULT TRUE,

  -- Sesión por inactividad (refresh token)
  refresh_jti VARCHAR(64),
  refresh_token_hash TEXT,
  last_activity_at TIMESTAMPTZ,

  fecha_creacion TIMESTAMPTZ NOT NULL DEFAULT now(),
  usuario_creacion VARCHAR(64),
  fecha_modificacion TIMESTAMPTZ NOT NULL DEFAULT now(),
  usuario_modificacion VARCHAR(64),

  CONSTRAINT fk_usuarios_persona_multiempresa
    FOREIGN KEY (empresa_id, persona_id)
    REFERENCES erp.personas(empresa_id, id),

  CONSTRAINT uq_usuarios_empresa_nombre_usuario UNIQUE (empresa_id, nombre_usuario)
);

CREATE INDEX IF NOT EXISTS ix_usuarios_empresa_activo
  ON erp.usuarios(empresa_id, activo);

CREATE INDEX IF NOT EXISTS ix_usuarios_last_activity_at
  ON erp.usuarios(last_activity_at);

COMMIT;

